import type { Metadata } from "next";
import { Beiruti } from 'next/font/google';
import './globals.css';

const beiruti = Beiruti({
  subsets: ['arabic', 'latin'], // Beiruti supports both
  weight: ['400', '700'],       // Choose the weights you need
  variable: '--font-beiruti',   // Define the CSS variable
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${beiruti.variable} ${beiruti.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
